import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowRight, Check, Hexagon, LockKeyhole, Mail, Moon, Sun, UserRound } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import toast from 'react-hot-toast';
import api from '../lib/api';

export default function LoginPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [firstName, setFirstName] = useState(''); const [lastName, setLastName] = useState(''); const [phone, setPhone] = useState(''); const [departmentId, setDepartmentId] = useState(''); const [position, setPosition] = useState(''); const [departments, setDepartments] = useState([]);
  const [remember, setRemember] = useState(false); const [dark, setDark] = useState(false); const [mode, setMode] = useState('signin'); const [loading, setLoading] = useState(false); const [resetPassword, setResetPassword] = useState('');
  const { login, completeOAuthLogin } = useAuth(); const navigate = useNavigate(); const [searchParams] = useSearchParams(); const isSignup = mode === 'signup'; const resetToken = searchParams.get('resetToken'); const isReset = Boolean(resetToken);
  useEffect(() => { const code = searchParams.get('oauthCode'); const error = searchParams.get('oauthError'); if (error) { toast.error(error); navigate('/login', { replace: true }); return; } if (!code) return; setLoading(true); completeOAuthLogin(code).then(({ user }) => { toast.success(user.isApproved ? 'Welcome back!' : 'Your account is awaiting administrator approval.'); navigate('/', { replace: true }); }).catch((err) => { toast.error(err.response?.data?.error || 'Sign-in could not be completed'); navigate('/login', { replace: true }); }).finally(() => setLoading(false)); }, [searchParams, completeOAuthLogin, navigate]);
  useEffect(() => { if (isSignup) api.get('/departments/public').then((res) => setDepartments(res.data)).catch(() => toast.error('Could not load departments.')); }, [isSignup]);
  const handleSubmit = async (event) => { event.preventDefault(); setLoading(true); try { if (isReset) { if (resetPassword && password !== resetPassword) throw new Error('Passwords do not match'); await api.post('/auth/reset-password', { token: resetToken, newPassword: password }); toast.success('Password reset successfully. Please sign in.'); navigate('/login', { replace: true }); return; } if (isSignup) { await api.post('/auth/register', { firstName, lastName, email, password, phone, departmentId, position }); const { user } = await login(email, password); toast.success(user.isApproved ? 'Account created!' : 'Account created and awaiting approval.'); } else { const { user } = await login(email, password); toast.success(user.isApproved ? 'Welcome back!' : 'Your account is awaiting administrator approval.'); } navigate('/'); } catch (err) { toast.error(err.response?.data?.error || err.message || (isSignup ? 'Could not create account' : 'Login failed')); } finally { setLoading(false); } };
  const requestPasswordReset = async () => { if (!email) return toast.error('Enter your email address first.'); try { await api.post('/auth/forgot-password', { email }); toast.success('If an account exists, a reset link has been sent.'); } catch { toast.error('Could not request a reset link. Please try again.'); } };
  const resendVerification = requestPasswordReset;
  const signInWith = (provider) => window.location.assign(`${import.meta.env.VITE_API_URL || '/api'}/auth/oauth/${provider}`);
  const switchMode = () => { setMode(isSignup ? 'signin' : 'signup'); setPassword(''); };
  return <main className={`login-page login-page--centered ${dark ? 'login-page--dark' : ''}`}>
    <div className="login-header login-header--floating"><button className="theme-toggle" type="button" onClick={() => setDark(!dark)} aria-label="Toggle light or dark theme"><Sun size={18} className={!dark ? 'active' : ''} /><Moon size={18} className={dark ? 'active' : ''} /></button></div>
    <section className="login-content"><div className="login-card-wrap"><section className="login-card" aria-labelledby="login-heading"><div className="login-card-logo"><Hexagon size={47} /></div><h1 id="login-heading">{isReset ? 'Reset Password' : isSignup ? 'Create Account' : 'Welcome Back'}</h1><p className="login-subtitle">{isReset ? 'Enter a new password below' : isSignup ? 'Join the BSC Management System' : 'Sign in to your BSC Management System'}</p>
      <form onSubmit={handleSubmit}>{isSignup && <><div className="signup-names"><div><label className="login-label" htmlFor="first-name">First Name</label><div className="login-input-wrap"><UserRound size={18} /><input id="first-name" value={firstName} onChange={(e) => setFirstName(e.target.value)} required /></div></div><div><label className="login-label" htmlFor="last-name">Last Name</label><div className="login-input-wrap"><UserRound size={18} /><input id="last-name" value={lastName} onChange={(e) => setLastName(e.target.value)} required /></div></div></div><label className="login-label" htmlFor="department">Department</label><select id="department" className="signup-select" value={departmentId} onChange={(e) => setDepartmentId(e.target.value)} required><option value="">Select your department</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select><label className="login-label" htmlFor="position">Position</label><select id="position" className="signup-select" value={position} onChange={(e) => setPosition(e.target.value)} required><option value="">Select your position</option><option>Employee</option><option>Officer</option><option>Analyst</option><option>Team Leader</option><option>Manager</option><option>Other</option></select><label className="login-label" htmlFor="phone">Phone Number</label><div className="login-input-wrap"><UserRound size={18} /><input id="phone" type="tel" value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="0912345678" required /></div></>}<label className="login-label" htmlFor="login-email">Email Address</label><div className="login-input-wrap"><Mail size={18} /><input id="login-email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Enter your email" required /></div><label className="login-label" htmlFor="login-password">Password</label><div className="login-input-wrap"><LockKeyhole size={18} /><input id="login-password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder={isSignup ? 'At least 8 characters' : 'Enter your password'} required /></div>{!isSignup && <div className="login-options"><label className="remember-check"><input type="checkbox" checked={remember} onChange={(e) => setRemember(e.target.checked)} /><span><Check size={12} /></span>Remember me</label><button type="button" onClick={resendVerification}>Forgot password?</button></div>}<button type="submit" disabled={loading} className="login-submit">{loading ? (isSignup ? 'Creating account…' : 'Signing in…') : <>{isSignup ? 'Create Account' : 'Sign In'} <ArrowRight size={21} /></>}</button></form>
      <div className="continue-divider"><span>or continue with</span></div><div className="social-logins"><button type="button" onClick={() => signInWith('google')}><b className="google-mark">G</b> Google</button><button type="button" onClick={() => signInWith('microsoft')}><span className="microsoft-mark"><i /><i /><i /><i /></span> Microsoft</button></div><p className="contact-admin">{isSignup ? 'Already have an account?' : 'New to BSC Management System?'} <button type="button" onClick={switchMode}>{isSignup ? 'Sign in' : 'Create an account'}</button></p>{isSignup && <p className="signup-note">New accounts need administrator approval before they can make changes.</p>}
    </section></div></section>
  </main>;
}
